<?php

return [
    'connection' => env('CBDB_CONNECTION'),
    'database' => env('CBDB_DATABASE'),
    'per_page' => env('CODES_PER_PAGE', 20),
    'tables' => [
        'ADDR_BELONGS_DATA',
        'ADDR_CODES',
        'ADDRESSES',
        'ALTNAME_CODES',
        'APPOINTMENT_CODES',
        'ASSOC_CODES',
        'ASSUME_OFFICE_CODES',
        'BIOG_ADDR_CODES',
        'BIOG_INST_CODES',
        'CBDB_NAME_LIST',
        'CBDB__NAME_FTS',
        'CBDB__TRAD_SIMP_MAP',
        'CHORONYM_CODES',
        'COUNTRY_CODES',
        'DYNASTIES',
        'ENTRY_CODES',
        'ETHNICITY_TRIBE_CODES',
        'EVENT_CODES',
        'EXTANT_CODES',
        'GANZHI_CODES',
        'HOUSEHOLD_STATUS_CODES',
        'INDEXYEAR_TYPE_CODES',
        'KINSHIP_CODES',
        'LITERARYGENRE_CODES',
        'MEASURE_CODES',
        'MERGED_PERSON_DATA',
        'OCCASION_CODES',
        'OFFICE_CODES',
        'PARENTAL_STATUS_CODES',
        'PLACE_CODES',
        'POSSESSION_ACT_CODES',
        'SCHOLARLYTOPIC_CODES',
        'SOCIAL_INSTITUTION_ALTNAME_CODES',
        'SOCIAL_INSTITUTION_CODES',
        'SOCIAL_INSTITUTION_NAME_CODES',
        'STATUS_CODES',
        'TEXT_BIBLCAT_CODES',
        'TEXT_CODES',
        'TEXT_INSTANCE_DATA',
        'TEXT_ROLE_CODES',
        'YEAR_RANGE_CODES',
    ],
];
