<?php

return [
    'connection' => env('CBDB_CONNECTION'),
    'database' => env('CBDB_DATABASE'),
    'per_page' => env('CODES_PER_PAGE', 20),

    // 僅從 /codes 首頁清單隱藏（不影響直連 /codes/{table}，也不影響 Query Playground / NL / MCP 白名單）。
    // 大小寫不敏感比對。設計見 docs/CODES_BOOLEAN_FILTER_DESIGN.md §9.1。
    'ui_hidden' => [
        'pinyin',
        'CBDB__TRAD_SIMP_MAP',
        'CBDB__NAME_FTS',
    ],

    // 可匯出為下游同步檔的表與其「有序欄位契約」。
    // 只有列在此處的表才開放 GET /codes/{table}/export；陣列順序即下游 .txt 的欄位順序。
    // endpoint 以 select(此順序) 輸出，與 live schema 物理欄序無關；並以 getColumnListing 驗證欄位存在性（fail-fast）。
    // 設計見 docs/OFFICE_CODES_EXPORT_SYNC.md。
    'export_columns' => [
        'OFFICE_CODES' => [
            'c_office_id',
            'c_dy',
            'c_office_pinyin',
            'c_office_chn',
            'c_office_pinyin_alt',
            'c_office_chn_alt',
            'c_office_trans',
            'c_office_trans_alt',
            'c_source',
            'c_pages',
            'c_notes',
        ],
    ],

    // 代碼表配置：鍵為表名，值為說明
    'tables' => [
        'ADDR_BELONGS_DATA' => '地址隸屬關係資料表',
        'ADDR_CODES' => '地址代碼表',
        'ADDRESSES' => '地址層級信息表（僅用於 API）',
        'ADMIN_CAT_CODES' => '行政類別代碼表',
        'ADMIN_CAT_CODE_TYPE_REL' => '行政類別代碼與類型關聯表',
        'ADMIN_CAT_TYPES' => '行政類別類型分類',
        'ALTNAME_CODES' => '別名類型代碼表',
        'ALTNAME_DATA' => '人物別名資料表',
        'APPOINTMENT_CODES' => '任命類型代碼表',
        'APPOINTMENT_CODE_TYPE_REL' => '任命代碼與類型關聯表',
        'APPOINTMENT_TYPES' => '任命類型分類',
        'ASSOC_CODES' => '社會關係代碼表',
        'ASSOC_CODE_TYPE_REL' => '社會關係代碼與類型關聯表',
        'ASSOC_DATA' => '社會關係資料表',
        'ASSOC_TYPES' => '社會關係大類',
        'ASSUME_OFFICE_CODES' => '就職方式代碼表',
        'BIOG_ADDR_CODES' => '傳記地址類型代碼表',
        'BIOG_ADDR_DATA' => '傳記地址資料表',
        'BIOG_INST_CODES' => '傳記機構類型代碼表',
        'BIOG_INST_DATA' => '傳記機構資料表',
        'BIOG_MAIN' => '人物傳記主表',
        'BIOG_SOURCE_DATA' => '傳記資料來源資料表',
        'BIOG_TEXT_DATA' => '傳記文本資料表',
        'CBDB__NAME_FTS' => '人名全文檢索表',
        'CBDB__TRAD_SIMP_MAP' => '繁簡字對照表',
        'CHORONYM_CODES' => '郡望代碼表',
        'COUNTRY_CODES' => '國家地區代碼表',
        'DYNASTIES' => '朝代信息表',
        'ENTRY_CODES' => '入仕途徑代碼表',
        'ENTRY_CODE_TYPE_REL' => '入仕代碼與類型關聯表',
        'ENTRY_DATA' => '人物入仕資料表',
        'ENTRY_TYPES' => '入仕途徑類型分類',
        'ETHNICITY_TRIBE_CODES' => '民族部族代碼表',
        'EVENTS_ADDR' => '事件地址資料表',
        'EVENTS_DATA' => '人物事件資料表',
        'EVENT_CODES' => '事件類型代碼表',
        'EXTANT_CODES' => '存世狀態代碼表',
        'GANZHI_CODES' => '干支紀年代碼表',
        'HOUSEHOLD_STATUS_CODES' => '戶籍身份代碼表',
        'INDEXYEAR_TYPE_CODES' => '索引年類型代碼表',
        'KINSHIP_CODES' => '親屬關係代碼表',
        'KIN_DATA' => '人物親屬關係資料表',
        'KIN_MOURNING' => '親屬服喪關係',
        'KIN_MOURNING_STEPS' => '親屬服喪等級',
        'LITERARYGENRE_CODES' => '文學體裁代碼表',
        'MEASURE_CODES' => '計量單位代碼表',
        'MERGED_PERSON_DATA' => '合併人物記錄',
        'NIAN_HAO' => '年號信息表',
        'OCCASION_CODES' => '場合事由代碼表',
        'OFFICE_CATEGORIES' => '官職分類',
        'OFFICE_CODES' => '官職代碼表',
        'OFFICE_CODE_TYPE_REL' => '官職代碼與類型關聯表',
        'OFFICE_TYPE_TREE' => '官職類型層級樹',
        'PARENTAL_STATUS_CODES' => '父母狀況代碼表',
        'pinyin' => '姓氏拼音對照表',
        'POSSESSION_ACT_CODES' => '財產行為代碼表',
        'POSSESSION_ADDR' => '財產地址資料表',
        'POSSESSION_DATA' => '財產資料表',
        'POSTED_TO_ADDR_DATA' => '任職地址資料表',
        'POSTED_TO_OFFICE_DATA' => '任職官署資料表',
        'POSTING_DATA' => '人物任職履歷資料表',
        'SCHOLARLYTOPIC_CODES' => '學術專題代碼表',
        'SOCIAL_INSTITUTION_ADDR' => '社會機構地址',
        'SOCIAL_INSTITUTION_ADDR_TYPES' => '社會機構地址類型',
        'SOCIAL_INSTITUTION_ALTNAME_CODES' => '社會機構別名代碼表',
        'SOCIAL_INSTITUTION_ALTNAME_DATA' => '社會機構別名資料表',
        'SOCIAL_INSTITUTION_CODES' => '社會機構代碼表',
        'SOCIAL_INSTITUTION_NAME_CODES' => '社會機構名稱代碼表',
        'SOCIAL_INSTITUTION_TYPES' => '社會機構類型分類',
        'STATUS_CODES' => '身份地位代碼表',
        'STATUS_CODE_TYPE_REL' => '身份代碼與類型關聯表',
        'STATUS_DATA' => '人物身份地位資料表',
        'STATUS_TYPES' => '身份地位類型分類',
        'TEXT_BIBLCAT_CODES' => '文獻分類代碼表',
        'TEXT_BIBLCAT_CODE_TYPE_REL' => '文獻分類代碼與類型關聯表',
        'TEXT_BIBLCAT_TYPES' => '文獻分類類型',
        'TEXT_CODES' => '文獻代碼表',
        'TEXT_INSTANCE_DATA' => '文獻版本資料表',
        'TEXT_ROLE_CODES' => '文獻角色代碼表',
        'TEXT_TYPE' => '文獻類型分類',
        'YEAR_RANGE_CODES' => '年份範圍代碼表',
    ],
];
